name: 'Library and demos build'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install depends
      run: sudo apt install meson libwayland-dev libgtk-3-dev gobject-introspection libgirepository1.0-dev gtk-doc-tools
    - name: Meson
      run: meson build -Dexamples=true -Ddocs=true
    - name: Build
      run: ninja -C build
